# Generated by Django 3.1.7 on 2021-03-19 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EggplantDataSheet', '0002_auto_20210319_0351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eggplantdatasheetdescription',
            name='accession_no',
        ),
        migrations.RemoveField(
            model_name='eggplantdatasheetdescription',
            name='plot_no',
        ),
        migrations.AddField(
            model_name='eggplantdatasheet',
            name='accession_no',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eggplantdatasheet',
            name='plot_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
