# Generated by Django 3.1.5 on 2021-01-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SweetPotato_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('planting_date', models.DateField()),
                ('sowing_date', models.DateField()),
                ('accession_no', models.CharField(max_length=50)),
                ('plot_no', models.IntegerField()),
                ('curator', models.CharField(max_length=50)),
                ('plant_growth_habit', models.IntegerField()),
                ('ground_cover', models.IntegerField()),
                ('twining', models.IntegerField()),
                ('predominant_vine_color', models.IntegerField()),
            ],
        ),
    ]
